inherit_from: .rubocop_todo.yml

require: rubocop-rails

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: disable
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'bin/bundle'
    - 'bin/yarn'
    - 'lib/generators/**/*'
    - 'config/spring.rb'
    - 'config/puma.rb'
    - '.irbrc'
    - 'lib/tasks/themes.rake'
    - 'lib/cli/**/*'
    - 'app/lib/story_pro.rb'
    - 'app/jobs/**/*'

